server:
  port: 8000

loadbalancer:
  coordinators:
    - url: http://localhost:7000
    - url: http://localhost:7001
  ollama:
    url: http://localhost:11434
    model: qwen2.5-coder:3b

spring:
  application:
    name: loadbalancer-service
